apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-gvsigonline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage