version: 2.1
orbs:
  doctl: digitalocean/cli@0.1.1
workflows:
  install_and_configure_cli:
    jobs:
      - doctl/install_and_initialize_cli:
          digitalocean-access-token: DO_TOKEN
      -  deploy
jobs:
  deploy:  
    # This is an example deploy job, not actually used by the workflow
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy to users
      - checkout
      - setup_remote_docker
      - doctl/install
      - run: 
          name: DigitalOcean Auth
          command: doctl auth init --access-token $DO_TOKEN
      - run:
          name: login to registry
          command: doctl registry login
      - run:
          name: Docker build image
          command: docker build -t cullera_test_ubuntu .
      - run:
          name: tag image
          command: docker tag cullera_test_ubuntu registry.digitalocean.com/lyn/cullera_test_ubuntu
      - run: 
          name: push image
          command: docker push registry.digitalocean.com/lyn/cullera_test_ubuntu
      - run:
          name: deploy image
          command: kubectl rollout restart deployment/gvsigonline-ubuntu